import { prisma } from "@/lib/prisma";

const CHAPTERS = [
  { code: "AKA", name: "Alaska Chapter NECA" },
  { code: "ABY", name: "Albany Chapter NECA" },
  { code: "ALB", name: "American Line Builders Chapter NECA" },
  { code: "ARI", name: "Arizona Chapter NECA" },
  { code: "ARK", name: "Arkansas Chapter NECA" },
  { code: "ATL", name: "Atlanta Chapter NECA" },
  { code: "ACC", name: "Atlantic Coast Chapter NECA" },
  { code: "BAT", name: "Baton Rouge Chapter NECA" },
  { code: "BOS", name: "Boston Chapter NECA" },
  { code: "CIN", name: "Cincinnati Chapter NECA" },
  { code: "CAL", name: "Cleveland Chapter NECA" },
  { code: "COL", name: "Colorado Chapter NECA" },
  { code: "CON", name: "Connecticut Chapter NECA" },
  { code: "DLS", name: "Dallas Chapter NECA" },
  { code: "DET", name: "Detroit Chapter NECA" },
  { code: "EAK", name: "Eastern Idaho Chapter NECA" },
  { code: "ECF", name: "Eastern Central Florida Chapter NECA" },
  { code: "ENJ", name: "Eastern New York Chapter NECA" },
  { code: "EPA", name: "Eastern Pennsylvania Chapter NECA" },
  { code: "ETX", name: "East Texas Chapter NECA" },
  { code: "FLA", name: "Florida West Coast Chapter NECA" },
  { code: "FOX", name: "Fox Valley Chapter NECA" },
  { code: "GCS", name: "Greater Cleveland Chapter NECA" },
  { code: "GKC", name: "Greater Kansas City Chapter NECA" },
  { code: "GTP", name: "Greater Tennessee Chapter NECA" },
  { code: "HOU", name: "Houston Chapter NECA" },
  { code: "ILL", name: "Illinois Chapter NECA" },
  { code: "IND", name: "Indiana Chapter NECA" },
  { code: "IOW", name: "Iowa Chapter NECA" },
  { code: "JAX", name: "Jacksonville Chapter NECA" },
  { code: "KTY", name: "Kentucky Chapter NECA" },
  { code: "LAC", name: "Los Angeles County Chapter NECA" },
  { code: "MCM", name: "Maine Chapter NECA" },
  { code: "MDC", name: "Maryland Chapter NECA" },
  { code: "MFS", name: "Memphis Chapter NECA" },
  { code: "MGC", name: "Michigan Chapter NECA" },
  { code: "MIN", name: "Minnesota Chapter NECA" },
  { code: "MMS", name: "Mississippi Chapter NECA" },
  { code: "MOB", name: "Mobile Chapter NECA" },
  { code: "MON", name: "Montana Chapter NECA" },
  { code: "NCA", name: "National Chapter NECA" },
  { code: "NEB", name: "Nebraska Chapter NECA" },
  { code: "NEV", name: "Nevada Chapter NECA" },
  { code: "NHV", name: "New Hampshire/Vermont Chapter NECA" },
  { code: "NJC", name: "New Jersey Chapter NECA" },
  { code: "NMX", name: "New Mexico Chapter NECA" },
  { code: "NOR", name: "North Central Florida Chapter NECA" },
  { code: "NOC", name: "North Coast Chapter NECA" },
  { code: "NTH", name: "North Texas Chapter NECA" },
  { code: "NYS", name: "New York State Chapter NECA" },
  { code: "OHI", name: "Ohio Chapter NECA" },
  { code: "OKL", name: "Oklahoma Chapter NECA" },
  { code: "ORE", name: "Oregon-Columbia Chapter NECA" },
  { code: "PEN", name: "Penn-Del-Jersey Chapter NECA" },
  { code: "PHI", name: "Philadelphia Chapter NECA" },
  { code: "PIT", name: "Pittsburgh Chapter NECA" },
  { code: "PSI", name: "Puget Sound Chapter NECA" },
  { code: "RGC", name: "Rio Grande Chapter NECA" },
  { code: "RIC", name: "Richmond Chapter NECA" },
  { code: "ROC", name: "Rochester Chapter NECA" },
  { code: "SCA", name: "San Diego Chapter NECA" },
  { code: "SFL", name: "South Florida Chapter NECA" },
  { code: "SJV", name: "San Joaquin Valley Chapter NECA" },
  { code: "SLC", name: "Southeastern Line Constructors Chapter NECA" },
  { code: "SNM", name: "Southern New Mexico Chapter NECA" },
  { code: "SOC", name: "Southern California Chapter NECA" },
  { code: "STL", name: "St. Louis Chapter NECA" },
  { code: "TAC", name: "Tacoma Chapter NECA" },
  { code: "TEX", name: "Texas Gulf Coast Chapter NECA" },
  { code: "TOL", name: "Toledo Chapter NECA" },
  { code: "UTA", name: "Utah Chapter NECA" },
  { code: "VIR", name: "Virginia Chapter NECA" },
  { code: "WAS", name: "Washington Chapter NECA" },
  { code: "WCC", name: "Western Central New York Chapter NECA" },
  { code: "WIS", name: "Wisconsin Chapter NECA" },
  { code: "WPA", name: "Western Pennsylvania Chapter NECA" },
  { code: "WYO", name: "Wyoming Chapter NECA" },
  { code: "ALA", name: "Alabama Chapter NECA" },
  { code: "AUG", name: "Augusta-Aiken Chapter NECA" },
  { code: "BCA", name: "Bakersfield Chapter NECA" },
  { code: "BDC", name: "Bluegrass Chapter NECA" },
  { code: "BTV", name: "Burlington Chapter NECA" },
  { code: "CAP", name: "Capital Chapter NECA" },
  { code: "CAS", name: "Cascade Chapter NECA" },
  { code: "CHA", name: "Chattanooga Chapter NECA" },
  { code: "CMB", name: "Columbus Chapter NECA" },
  { code: "CNY", name: "Central New York Chapter NECA" },
  { code: "DAY", name: "Dayton-Miami Valley Chapter NECA" },
  { code: "DEL", name: "Delaware Chapter NECA" },
  { code: "FAR", name: "Far West Chapter NECA" },
  { code: "GEO", name: "Georgia Chapter NECA" },
  { code: "HAW", name: "Hawaii Chapter NECA" },
  { code: "HVC", name: "Hudson Valley Chapter NECA" },
  { code: "IEC", name: "Intermountain Chapter NECA" },
  { code: "KOO", name: "Kansas Chapter NECA" },
  { code: "LOU", name: "Louisiana Chapter NECA" },
  { code: "MDC2", name: "Metro DC Chapter NECA" },
  { code: "MID", name: "Midwestern Chapter NECA" },
  { code: "MOH", name: "Mohawk Valley Chapter NECA" },
  { code: "MSC", name: "Monmouth/Ocean Chapter NECA" },
  { code: "NAG", name: "Niagara Frontier Chapter NECA" },
  { code: "NCR", name: "North Carolina Chapter NECA" },
  { code: "NOL", name: "New Orleans Chapter NECA" },
  { code: "NVL", name: "Nashville Chapter NECA" },
  { code: "OHV", name: "Ohio Valley Chapter NECA" },
  { code: "PAS", name: "Pasadena & Foothill Chapter NECA" },
  { code: "RAL", name: "Raleigh-Durham Chapter NECA" },
  { code: "SAC", name: "Sacramento Valley Chapter NECA" },
  { code: "SAR", name: "Sarasota-Manatee Chapter NECA" },
  { code: "SAV", name: "Savannah Chapter NECA" },
  { code: "SEA", name: "Seattle Chapter NECA" },
  { code: "SEM", name: "Southeastern Michigan Chapter NECA" },
  { code: "SHR", name: "Shenandoah Valley Chapter NECA" },
  { code: "SPC", name: "Southwest Pacific Chapter NECA" },
  { code: "TAL", name: "Tallahassee Chapter NECA" },
  { code: "TAM", name: "Tampa Chapter NECA" },
  { code: "TRI", name: "Tri-City Chapter NECA" },
  { code: "TUL", name: "Tulsa Chapter NECA" },
  { code: "W OH", name: "Western Ohio Chapter NECA" },
  { code: "WNY", name: "Western New York State Chapter NECA" }
];

async function main() {
  for (const chapter of CHAPTERS) {
    await prisma.chapter.upsert({
      where: { name: chapter.name },
      update: {
        code: chapter.code,
        isActive: true,
        deletedAt: null,
      },
      create: {
        name: chapter.name,
        code: chapter.code,
        isActive: true,
      },
    });
  }

  console.log(`Seeded ${CHAPTERS.length} chapters.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error("Failed to seed chapters:");
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });